name: caipoappv0
description: "flomad_caipo"
publish_to: 'none' # Not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase - using a known compatible set of versions
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  # firebase_crashlytics: ^4.3.4
  google_sign_in: ^6.2.1
  desktop_webview_auth: 0.0.12
  url_launcher: ^6.2.5
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^0.13.6
  
  # UI components
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  google_fonts: 4.0.4
  
  # State management
  provider: ^6.1.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Utilities
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  file_picker: ^9.0.2
  speech_to_text: ^7.0.0
  xml: ^6.5.0
  
  # APIs
  dialogflow_flutter: 1.0.0
  googleapis_auth: 1.4.1
  flutter_sound: ^9.2.13
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  audio_waveforms: ^1.0.4
  video_player: ^2.8.3
  permission_handler: ^11.3.0
  path: ^1.9.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.25.7 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env