// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3chZOV8Vs2dDHzNriwekpnJ76eSAZXw',
    appId: '1:523970252754:web:9ff3f1069320b4f991820b',
    messagingSenderId: '523970252754',
    projectId: 'caipo-mobile-8aa1c',
    authDomain: 'caipo-mobile-8aa1c.firebaseapp.com',
    storageBucket: 'caipo-mobile-8aa1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7i6wgC_61QXqbUWr0Nc_5yGy6kAZEHw',
    appId: '1:523970252754:android:82bfec306ba4560791820b',
    messagingSenderId: '523970252754',
    projectId: 'caipo-mobile-8aa1c',
    storageBucket: 'caipo-mobile-8aa1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHU9e-UdKJA_9fUahAzPurZpW6z-o7GE',
    appId: '1:523970252754:ios:aed69ce7245f5f9491820b',
    messagingSenderId: '523970252754',
    projectId: 'caipo-mobile-8aa1c',
    storageBucket: 'caipo-mobile-8aa1c.firebasestorage.app',
    androidClientId: '523970252754-0ir6826s7fhhfbghe5i2sqsgj3o30q6b.apps.googleusercontent.com',
    iosClientId: '523970252754-ikdqtsur14au8niter1r289qr79jh1ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.caipoappv0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEHU9e-UdKJA_9fUahAzPurZpW6z-o7GE',
    appId: '1:523970252754:ios:aed69ce7245f5f9491820b',
    messagingSenderId: '523970252754',
    projectId: 'caipo-mobile-8aa1c',
    storageBucket: 'caipo-mobile-8aa1c.firebasestorage.app',
    androidClientId: '523970252754-0ir6826s7fhhfbghe5i2sqsgj3o30q6b.apps.googleusercontent.com',
    iosClientId: '523970252754-ikdqtsur14au8niter1r289qr79jh1ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.caipoappv0',
  );

static const FirebaseOptions windows = FirebaseOptions(
  apiKey: 'AIzaSyDj3chZOV8Vs2dDHzNriwekpnJ76eSAZXw',
  appId: '1:523970252754:web:9ff3f1069320b4f991820b',
  messagingSenderId: '523970252754',
  projectId: 'caipo-mobile-8aa1c',
  authDomain: 'caipo-mobile-8aa1c.firebaseapp.com',
  storageBucket: 'caipo-mobile-8aa1c.firebasestorage.app',
);


}